library_name: hyper_decoder_y_sim
target_abis: [arm64-v8a]
models:
  hyper_decoder_y_sim:
    platform: onnx
    model_file_path: path/to/model/hyper_decoder_y.onnx
    subgraphs:
      - input_tensors:
          - 'input'
        input_data_formats: NCHW
        input_shapes:
          - 1,128,16,16
        output_tensors:
          - 'result.27'
        output_shapes:
          - 1,128,64,64
        output_data_formats: NCHW
        backend: caffe2
    cl_mem_type: image
    runtime: gpu
    winograd: 4
    data_type: float16_float32
    load_from_im: False
    executing_only:
      # CPU: ["Conv_57", "Reshape_58", "Transpose_59", "Concat_66"]
